---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-catalog-root
  description: Root catalog for all entities
spec:
  targets:
    - ./components/*.yaml
    - ./templates/github/*.yaml
    - ./systems/*.yaml
