---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: neuvector-upgrade-responder
  description: Neuvector upgrade-responder service
  annotations:
    backstage.io/kubernetes-id: neuvector-upgrade-responder
    github.com/project-slug: rancher/upgrade-responders
spec:
  type: service
  lifecycle: development
  owner: neuvector
  system: applications
