---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: request-secret-access
  title: Request Secret Access
  description: Request secret access for a Git repository (e.g dockerhub, rancher prime secrets etc)
  tags:
    - secrets
    - vault
    - self-service
spec:
  owner: group:eio
  type: service
  system: secrets-management
  parameters:
    - title: Secret Access Request
      required:
        - org
        - repoName
        - secretType
      properties:
        org:
          title: GitHub Organization
          type: string
          description: Which GitHub organization owns this repository
          default: rancher
          enum:
            - rancher
            - rancher-eio
            - rancherlabs
            - k3s-io
        repoName:
          title: Repository Name
          type: string
          description: The repository that needs secret access
          ui:autofocus: true
          ui:help: Enter the repository name (e.g test-repo)
        secretType:
          title: Secret Type
          type: string
          enum:
            - dockerhub
            - rancherprime
            - rancherprime-stg
          enumNames:
            - 'DockerHub Registry'
            - 'Rancher Prime Registry'
            - 'Rancher Prime Staging Registry'
          description: Type of secret needed

    - title: Additional Information
      properties:
        justification:
          title: Why does this repository need access to this secret?
          type: string
          ui:widget: textarea
          ui:options:
            rows: 3

  steps:
    - id: create-issue
      name: Create Tracking Issue
      action: github:issues:create
      input:
        repoUrl: github.com?owner=rancher-eio&repo=issues
        # repoUrl:: owner=rancherlabs&repo=eio
        title: 'Secret Access Request: ${{ parameters.secretType }} for ${{ parameters.org }}/${{ parameters.repoName }}'

        body: |
          ## Secret Access Request

          **Repository:** `${{ parameters.org }}/${{ parameters.repoName }}`
          **Secret Type:** `${{ parameters.secretType }}`
          **Requested By:** @${{ user.entity.metadata.name }}

          ### Justification
          ${{ parameters.justification }}

          ---
          *This issue was automatically created by Backstage*

        labels:
          - secret-access-request
          - automated

    - id: trigger-workflow
      name: Trigger Secret Access Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?owner=rancher&repo=testing
        # repoUrl: github.com?repo=org&owner=${{ parameters.org }}
        workflowId: request-access-secret.yaml
        branchOrTagName: main
        workflowInputs:
          repo-name: ${{ parameters.repoName }}
          org: ${{ parameters.org }}
          secret-type: ${{ parameters.secretType }}
          requestedBy: ${{ user.entity.metadata.name }}
          issueNumber: ${{ steps['create-issue'].output.issueNumber | string }}
          issueRepo: rancher-eio/issues
          # issueRepo: rancherlabs/eio

  output:
    text:
      - title: Secret Request Submitted!
        content: |
          ✅ **Request Created**

          Your secret access request for `${{ parameters.org }}/${{ parameters.repoName }}`  is being processed.

          **You'll receive GitHub notifications at each stage:**
          1. PR created (~2 min)
          2. EIO team review (1-3 days)
          3. Secret ready (~5 min after merge)

          All updates will be posted to the tracking issue below.

    links:
      - title: View Workflow
        icon: dashboard
        url: 'https://github.com/rancher/testing/actions/workflows/request-access-secret.yaml'
        # url: https://github.com/${{ parameters.org }}/internal-production/actions/workflows/request-access-secret.yaml

      - title: Track Request
        icon: github
        url: ${{ steps['create-issue'].output.issueUrl }}
