---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-repo
  title: Create GitHub Repository
  description: Create a new GitHub repository via Crossplane
  tags:
    - github
    - repository
    - self-service
spec:
  owner: group:eio
  type: service
  system: github-management
  parameters:
    - title: Repository Details
      required:
        - org
        - name
        - visibility
      properties:
        org:
          title: GitHub Organization
          type: string
          description: Which org should this repo be created in?
          enum: [rancher, rancherlabs, rancher-eio]
          default: rancher
          ui:autofocus: true

        name:
          title: Repository Name
          type: string
          description: Name of the repository (without org prefix)
          pattern: '^[a-z0-9-]+$'
          ui:help: Lowercase letters, numbers, and hyphens only

        visibility:
          title: Visibility
          type: string
          description: Who can see this repository?
          enum: [private, public, internal]
          default: private

        description:
          title: Description
          type: string
          ui:widget: textarea

    - title: Additional Information
      properties:
        justification:
          title: Why do you need this repo?
          type: string
          ui:widget: textarea
          ui:options:
            rows: 3

  steps:
    - id: create-issue
      name: Creating issue for tracking
      action: github:issues:create
      input:
        repoUrl: github.com?repo=issues&owner=rancher-eio
        title: 'Create Repository Request: ${{ parameters.org }}/${{ parameters.name }}'
        body: |
          ## Create Repository Request

          **Repository:** `${{ parameters.org }}/${{ parameters.name }}`
          **Organization:** ${{ parameters.org }}
          **Visibility:** `${{ parameters.visibility }}`
          **Requested by:** @${{ user.entity.metadata.name }}

          ### Description
          ${{ parameters.description }}

          ### Justification
          ${{ parameters.justification }}

          ---

          ## Progress

          - [ ] Pull request created
          - [ ] EIO team review
          - [ ] Pull request merged
          - [ ] Flux sync
          - [ ] Repository provisioned

          ---

          _This issue will be automatically updated as your request progresses._
        labels:
          - backstage-request
          - github
          - resolution-automated

    - id: trigger-workflow
      name: Triggering workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=org&owner=${{ parameters.org }}  # This is where the workflow lives
        workflowId: add-repository.yaml
        branchOrTagName: main
        workflowInputs:
          name: ${{ parameters.name }}
          org: ${{ parameters.org }}
          visibility: ${{ parameters.visibility }}
          description: ${{ parameters.description }}
          justification: ${{ parameters.justification }}
          requestedBy: ${{ user.entity.metadata.name }}
          issueNumber: ${{ steps['create-issue'].output.issueNumber }}
          issueRepo: rancher-eio/issues

  output:
    text:
      - title: Repository Request Submitted!
        content: |
          ✅ **Request Created**

          Your repository request for `${{ parameters.org }}/${{ parameters.name }}` is being processed.

          **You'll receive GitHub notifications at each stage:**
          1. PR created (~2 min)
          2. EIO team review (1-3 days)
          3. Repository ready (~5 min after merge)

          All updates will be posted to the tracking issue below.

    links:
      - title: View Workflow
        icon: dashboard
        url: https://github.com/${{ parameters.org }}/org/actions/workflows/add-repository.yaml

      - title: Track Request
        icon: github
        url: ${{ steps['create-issue'].output.issueUrl }}
