apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-create-repo
  title: Create GitHub Repository
  description: Create a new GitHub repository (creates PR for EIO team approval)
  tags:
    - github
    - repository
    - self-service
spec:
  owner: group:eio
  type: service
  system: github-management
  parameters:
    - title: Repository Details
      required:
        - org
        - name
        - visibility
      properties:
        org:
          title: GitHub Org
          type: string
          description: Which org should this repo be created in?
          enum:
            - rancher
            - rancherlabs
            - rancher-eio
          enumNames:
            - Rancher
            - RancherLabs
            - Rancher EIO
          default: rancher
          ui:autofocus: true

        name:
          title: Repository Name
          type: string
          description: Name of the repository (without org prefix)
          pattern: '^[a-z0-9-]+$'
          ui:help: Lowercase letters, numbers, and hyphens only

        visibility:
          title: Visibility
          type: string
          description: Who can see this repository?
          enum:
            - private
            - public
            - internal
          enumNames:
            - Private
            - Public
            - Internal
          default: private

    - title: Additional Information
      properties:
        justification:
          title: Why do you need this repo?
          type: string
          ui:widget: textarea
          ui:options:
            rows: 3

  steps:
    - id: trigger-workflow
      name: Trigger Repository Creation Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=org&owner=${{ parameters.org }}
        workflowId: add-repository.yaml
        branchOrTagName: main
        workflowInputs:
          name: ${{ parameters.name }}
          visibility: ${{ parameters.visibility }}

  output:
    links:
      - title: View Pull Requests
        icon: github
        url: https://github.com/${{ parameters.org }}/org/pulls
      - title: View Workflow Runs
        icon: dashboard
        url: https://github.com/${{ parameters.org }}/org/actions/workflows/add-repository.yaml
