---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: secrets-management
  title: Secrets Management
  description: Secrets to be created in Vault for workflows to consume
  tags:
    - vault
    - infrastructure
  annotations:
    github.com/team-slug: rancher-eio/eio
spec:
  owner: eio
